### ISSUE TITLE
version 1.3.4

### ISSUE THREAD

**Issue by steom** [Killeroo/PowerPing#135] opened 2024-02-05 07:42 UTC
Listening for ICMP Packets
Unhandled exception. System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array , Int32 , Array , Int32 , Int32 )
   at PowerPing.ICMP..ctor(Byte[] data, Int32 size, Int32 offset)
   at PowerPing.Listen.ListenForICMPOnAddress(IPAddress address)
   at PowerPing.Listen.<>c__DisplayClass1_1.<Start>b__0()
   at System.Threading.Thread.StartCallback()

**Comment by Killeroo** [comment] 2024-02-05 22:14
I'm sorry I could not reproduce this, could you give some more details so I can debug this further, any info like:

- How frequently this occurs
- A screenshot of PowerPing before the exception
- What platform and OS you are running on
- What type of ping you were listening for when this happened (if known) 

Thanks

**Comment by Killeroo** [comment] 2024-06-05 21:52
I've added a speculative fix that should stop this from happening in the [latest release](https://github.com/Killeroo/PowerPing/releases/latest). Please let me know if it keeps occuring.

**Comment by Killeroo** [comment] 2024-06-11 21:50
Glad to hear that, closing this issue for now then 👍

**Closed by Killeroo** 2024-06-11 21:50 UTC
